{{- if .Values.cloud.azure.useKeyVault -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profisee-keyvault
spec:
  selector:
    matchLabels:
      app: profisee-keyvault
  replicas: 1
  template:
    metadata:
      labels:
        app: profisee-keyvault
        aadpodidbinding: azure-pod-identity-binding-selector
    spec:
      terminationGracePeriodSeconds: 60
      nodeSelector:
            "kubernetes.io/os": linux
      #serviceAccountName: profiseeserviceaccount
      #automountServiceAccountToken: false
      containers:
        - name: profisee-keyvault
          image: docker.io/library/alpine:latest
          imagePullPolicy: Always
          command:
            - /bin/sh
            - "-c"
            - "while sleep 3600; do :; done"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kvname
{{- end }}