controller: 
  extraArgs: 
    default-ssl-certificate: profisee/profisee-tls-ingress
  nodeSelector: 
    kubernetes.io/os: linux
  replicaCount: 1
  admissionWebhooks:
    patch:
      nodeSelector:
        kubernetes.io/os: linux
  config:
    proxy-buffering: "off"
    proxy-buffer-size: "512k"
    proxy-connect-timeout: "5400"
    proxy-send-timeout: "5400"
    proxy-read-timeout: "5400"
    proxy-next-upstream: "off"
    proxy-request-buffering: "off"
    proxy-buffers: "32 512k"
    proxy-busy-buffers-size: "512k"
    client_body_buffer_size: "512k"
    client-header-buffer-size: "512k"    
    http2-max-field-size: "16k"
    http2-max-header-size: "512k"
    large-client-header-buffers: "32 512k"
    
defaultBackend: 
  nodeSelector: 
    kubernetes.io/os: linux

